bootstrap:
  n_iter: 100
chandra-data:
  name: e0102-zoom-a
  path_data: data
  obs_ids:
    - 8365
    - 6766
    - 9694
    - 15467
    - 14258
    - 13093
    - 11957
    - 6759
    - 17380
    - 26987
    - 25618
    - 22805
    - 21804
    - 20639
    - 19850
    - 18418
    - 24577
    - 17688
    - 16589
    - 6758
    - 10656
    - 6765
    - 10654
    - 10655
  obs_id_ref: 8365
  roi:
    center:
      frame: icrs
      lon:  "16.017d"
      lat: "-72.034d"
    width: 15 arcsec
    bin_size: 0.25
    energy_range:
      min: 0.5 keV
      max: 7 keV
  psf_simulator: marx
  irfs:
    e0102-zoom-a:
      spectrum:
        center:
          frame: icrs
          lon: "16.017d"
          lat: "-72.034d"
        radius: 0.3 arcmin
        energy_range:
          min: 0.5 keV
          max: 7.0 keV
        energy_groups: 5
        energy_step: 0.01
      psf:
        blur: 0.07
        readout_streak: false
        pileup: false
        extended: true
        minsize: 125
        numiter: 100
  ciao:
    chandra_repro:
      cleanup: true
      clobber: true
